import 'package:attendance_mobile/src/core/theme/app_colors.dart';
import 'package:attendance_mobile/src/presentation/viewmodels/attendance_state.dart';
import 'package:flutter/material.dart';

extension AttendancePresentation on AttendanceState {
  int get progressIndex => switch (step) {
    AttendanceStep.ready || AttendanceStep.permission => 0,
    AttendanceStep.location => 1,
    AttendanceStep.camera => 2,
    AttendanceStep.submitting ||
    AttendanceStep.success ||
    AttendanceStep.failure => 3,
  };

  Color get stateColor => switch (step) {
    AttendanceStep.failure || AttendanceStep.permission => AppBrand.danger,
    AttendanceStep.success => AppBrand.success,
    _ => AppBrand.mint,
  };

  IconData get icon => switch (step) {
    AttendanceStep.success => Icons.check_circle_outline_rounded,
    AttendanceStep.failure || AttendanceStep.permission => Icons.error_outline,
    AttendanceStep.location => Icons.my_location_rounded,
    AttendanceStep.camera => Icons.camera_alt_outlined,
    AttendanceStep.submitting => Icons.cloud_upload_outlined,
    AttendanceStep.ready => Icons.face_retouching_natural_rounded,
  };

  String get title => switch (step) {
    AttendanceStep.ready => 'Verify your attendance',
    AttendanceStep.permission => 'Permission required',
    AttendanceStep.location => 'Getting your location',
    AttendanceStep.camera => 'Preparing the camera',
    AttendanceStep.submitting => 'Verifying your identity',
    AttendanceStep.success => 'Attendance recorded',
    AttendanceStep.failure => 'Could not record attendance',
  };

  String get description =>
      message ??
      switch (step) {
        AttendanceStep.ready =>
          'We will collect a fresh location and selfie for secure verification.',
        AttendanceStep.permission =>
          'Camera and precise foreground location are required for check-in.',
        AttendanceStep.location =>
          'Keep the app open while an accurate location is acquired.',
        AttendanceStep.camera =>
          'Use even light, remove obstructions, and look toward the camera.',
        AttendanceStep.submitting =>
          'Keep this screen open while the server verifies your check-in.',
        AttendanceStep.success =>
          'The timestamp below was generated by the attendance service.',
        AttendanceStep.failure =>
          'Review the error and capture a fresh selfie before retrying.',
      };
}
