from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from .domain import Attendance, CaptureSession, FaceDecision, Principal, Staff


class AuthPort(Protocol):
    async def login(self, email: str, password: str) -> tuple[str, str, Principal]: ...
    async def authenticate(self, access_token: str) -> Principal: ...
    async def refresh(self, refresh_token: str) -> tuple[str, str, Principal]: ...
    async def logout(self, access_token: str) -> None: ...


class Repository(Protocol):
    async def list_staff(self) -> Sequence[Staff]: ...
    async def create_staff(self, name: str, employee_id: str) -> Staff: ...
    async def get_staff(self, staff_id: UUID) -> Staff | None: ...
    async def save_staff(self, staff: Staff, enrolment_image_ids: Sequence[UUID]) -> None: ...
    async def create_capture(self, capture: CaptureSession) -> None: ...
    async def get_capture(self, capture_id: UUID) -> CaptureSession | None: ...
    async def consume_capture(self, capture_id: UUID) -> None: ...
    async def get_attendance_for_date(self, staff_id: UUID, day: object) -> Attendance | None: ...
    async def create_attendance(
        self,
        attendance: Attendance,
        actor_id: UUID,
        operation_key: UUID,
        capture_id: UUID,
    ) -> Attendance: ...
    async def list_attendance(self, staff_id: UUID) -> Sequence[Attendance]: ...
    async def get_operation(self, actor_id: UUID, key: UUID) -> Attendance | None: ...


class FaceVerifier(Protocol):
    async def enrol(self, images: Sequence[bytes]) -> FaceDecision: ...
    async def verify(self, enrolled_template: bytes, image: bytes) -> FaceDecision: ...


class ImageStore(Protocol):
    async def put_attendance_image(self, staff_id: UUID, content: bytes) -> UUID: ...
    async def put_enrolment_images(
        self, staff_id: UUID, contents: Sequence[bytes]
    ) -> Sequence[UUID]: ...
    async def signed_url(self, image_id: UUID, principal: Principal) -> tuple[str, datetime]: ...
